# Transcript selection

In [1]:
import pandas as pd
import csv
from utils.constants import Paths

In [2]:
# path = Paths.mccray_modified_metadata
path = r"../data/mccray/october_sprint/mccray d_main.csv"
df = pd.read_csv(path)
df

,Title,Creator,Contributors,Date,Approximate Date,Source,Subject,Local Subject,S.C. County,Description,...,Original Len,Special Pattern,General Pattern,Repeat Chars,Short/No Transcript,Quality,Issue Types,Detected Artifacts,Semi-clean Transcript,% English
0,Afro-American Newsboy Application signed by Mr...,NaN,"McCray, John Henry, 1910-1987",NaN,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,An application to be a Newsboy for the Afro-Am...,...,213,False,False,False,False,True,[],[],-5491 AFRO-AMERICAN NEWSBOY'S APPLICATION I he...,78.378378
1,Lighthouse Informer receipt,NaN,"McCray, John Henry, 1910-1987",NaN,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,A blank Lighthouse and Informer receipt.,...,121,False,False,False,False,True,[],[],"19 Received from RECEIVED OF ""Shedding Light F...",91.304348
2,"The Lighthouse Solicitor's Record, Home Office...",NaN,"McCray, John Henry, 1910-1987",NaN,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,"A solicitor's record, home office order, and s...",...,392,False,False,False,False,True,[],[],SOLICITOR'S RECORD Name Address City State Amo...,91.666667
3,The Lighthouse Remittance Envelope(Front),NaN,"McCray, John Henry, 1910-1987",NaN,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,The front of a Lighthouse remittance envelope.,...,72,False,False,False,False,True,[],[],Sender's Address Shedding Light For A Growing ...,100.000000
4,"Advertisment, Chicken Special at the Pig Trail...",NaN,"McCray, John Henry, 1910-1987",NaN,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,An ad about the Chicken Special for the Pig Tr...,...,161,False,False,False,False,True,[],[],"Just Telephone Us, Place your order. It'll be ...",84.848485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11815,"Letter from John F. Potts, Director of Avery I...","Potts, John F. (Director of Avery Institute)","McCray, John Henry, 1910-1987",1946-09-26 00:00:00,NaN,Manuscripts; Accession 11294.,Avery Normal Institute;Lighthouse and Informer,NaN,NaN,"Letter from John F. Potts, Director of Avery I...",...,361,False,False,False,False,True,[],[],Charleston 16. S. C.\nOFFICE OF THE DIRECTOR\n...,80.645161
11816,"Letter from Mildred Chestnut, Secretary at the...","Chestnut, Mildred (Secretary for Lighthouse an...","McCray, John Henry, 1910-1987",1946-09-27 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,"Letter from Mildred Chestnut, Secretary at the...",...,300,True,False,False,False,False,['Special Char Artifacts'],['┬Ñ'],"September 27, W46\nfthelyn Psxkex 163a Line St...",79.661017
11817,Letter from John H. McCray to Mr. Arthur W. Ai...,"McCray, John Henry, 1910-1987","McCray, John Henry, 1910-1987",1946-09-28 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,Letter from John H. McCray to Mr. Arthur W. Ai...,...,208,False,False,False,False,True,[],[],"Sept. 28, 1946\nMX* Ait hoi W* Aiken\n429 Pace...",73.809524
11818,"Letter from John H. McCray to Dr. E. J. Cling,...","McCray, John Henry, 1910-1987","McCray, John Henry, 1910-1987",1946-09-28 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,Letter from John H. McCray to Dr. E. J. Cling ...,...,213,True,True,False,False,False,"['Special Char Artifacts', 'General Artifacts']","['┬ú&ΓÇó', '┬úΓÇó', '\\\\\\\\', '\\\\\\\\', 'Γ...","Sept. 28, 1946\nJ. Cling\n583 King St.\nCharle...",90.476190
11819,Letter from Mrs. E.M. Parker to Mildred Chestn...,"McCray, John Henry, 1910-1987","McCray, John Henry, 1910-1987",1946-09-30 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,Letter from Mrs. E.M. Parker to Mildred Chestn...,...,505,True,False,False,False,False,['Special Char Artifacts'],['ΓÇÖ'],"loja Line, St.\nCharleston, S.C\nSept. 30,1946...",96.385542

In [3]:

start_year = 1940
end_year = 1950

display(df[['Title', 'Year']])

df = df[df['Year'] >= start_year]
df = df[df['Year'] <= end_year]

display(df[['Title', 'Year']])

                                                   Title    Year
0      Afro-American Newsboy Application signed by Mr...     NaN
1                            Lighthouse Informer receipt     NaN
2      The Lighthouse Solicitor's Record, Home Office...     NaN
3              The Lighthouse Remittance Envelope(Front)     NaN
4      Advertisment, Chicken Special at the Pig Trail...     NaN
...                                                  ...     ...
11815  Letter from John F. Potts, Director of Avery I...  1946.0
11816  Letter from Mildred Chestnut, Secretary at the...  1946.0
11817  Letter from John H. McCray to Mr. Arthur W. Ai...  1946.0
11818  Letter from John H. McCray to Dr. E. J. Cling,...  1946.0
11819  Letter from Mrs. E.M. Parker to Mildred Chestn...  1946.0

[11820 rows x 2 columns]

                                                   Title    Year
681    Certificate that Mr. Henry Smith is a member o...  1942.0
699                      New Subscriptions, 1964, Page 1  1946.0
700                      New Subscriptions, 1964, Page 3  1946.0
701                                           Price List  1946.0
702                     Special offer for Mrs. S. Bailey  1946.0
...                                                  ...     ...
11815  Letter from John F. Potts, Director of Avery I...  1946.0
11816  Letter from Mildred Chestnut, Secretary at the...  1946.0
11817  Letter from John H. McCray to Mr. Arthur W. Ai...  1946.0
11818  Letter from John H. McCray to Dr. E. J. Cling,...  1946.0
11819  Letter from Mrs. E.M. Parker to Mildred Chestn...  1946.0

[3438 rows x 2 columns]

In [4]:
list(df)
df

,Title,Creator,Contributors,Date,Approximate Date,Source,Subject,Local Subject,S.C. County,Description,...,Original Len,Special Pattern,General Pattern,Repeat Chars,Short/No Transcript,Quality,Issue Types,Detected Artifacts,Semi-clean Transcript,% English
681,Certificate that Mr. Henry Smith is a member o...,NaN,"McCray, John Henry, 1910-1987","February, 1942",NaN,Manuscripts; Accession 11294.,NAACP,NaN,NaN,A certificate that Mr. Henry Smith is a member...,...,312,True,True,True,False,False,"['Special Char Artifacts', 'General Artifacts'...","['ΓÇó$', '%\\\\\\\\', '^^*^^^', '^^^', '^^', '...",i Class) $1.00\n,100.000000
699,"New Subscriptions, 1964, Page 1",NaN,"McCray, John Henry, 1910-1987",1946,NaN,Manuscripts; Accession 11294.,The Lighthouse and Informer,NaN,NaN,A document listing the new subscriptions made ...,...,116,False,False,False,False,True,[],[],York Holly Hill Holly Hill City A i k en Gresh...,80.000000
700,"New Subscriptions, 1964, Page 3",NaN,"McCray, John Henry, 1910-1987",1946,NaN,Manuscripts; Accession 11294.,The Lighthouse and Informer,NaN,NaN,A document listing the new subscriptions made ...,...,1291,False,False,False,False,True,[],[],"APRlL, 1946 Richard Corley New Haven, Conn. W....",71.559633
701,Price List,NaN,"McCray, John Henry, 1910-1987",1946,NaN,Manuscripts; Accession 11294.,The Lighthouse and Informer,NaN,NaN,A document with the price list for the Lightho...,...,458,True,False,False,False,False,['Special Char Artifacts'],"['ΓÇö', 'ΓÇö', 'ΓÇö', 'ΓÇö']","Price List Public Notice Memorials, Cards of T...",79.518072
702,Special offer for Mrs. S. Bailey,NaN,"McCray, John Henry, 1910-1987",1946,NaN,Manuscripts; Accession 11294.,The Lighthouse and Informer,NaN,NaN,A special offer for Mrs. S. Bailey from the Li...,...,544,True,True,False,False,False,"['Special Char Artifacts', 'General Artifacts']","['┬½', 'lt;f&gt']",SPECIAL OFFER\nGood Until Friday July 22 this ...,92.452830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11815,"Letter from John F. Potts, Director of Avery I...","Potts, John F. (Director of Avery Institute)","McCray, John Henry, 1910-1987",1946-09-26 00:00:00,NaN,Manuscripts; Accession 11294.,Avery Normal Institute;Lighthouse and Informer,NaN,NaN,"Letter from John F. Potts, Director of Avery I...",...,361,False,False,False,False,True,[],[],Charleston 16. S. C.\nOFFICE OF THE DIRECTOR\n...,80.645161
11816,"Letter from Mildred Chestnut, Secretary at the...","Chestnut, Mildred (Secretary for Lighthouse an...","McCray, John Henry, 1910-1987",1946-09-27 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,"Letter from Mildred Chestnut, Secretary at the...",...,300,True,False,False,False,False,['Special Char Artifacts'],['┬Ñ'],"September 27, W46\nfthelyn Psxkex 163a Line St...",79.661017
11817,Letter from John H. McCray to Mr. Arthur W. Ai...,"McCray, John Henry, 1910-1987","McCray, John Henry, 1910-1987",1946-09-28 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,Letter from John H. McCray to Mr. Arthur W. Ai...,...,208,False,False,False,False,True,[],[],"Sept. 28, 1946\nMX* Ait hoi W* Aiken\n429 Pace...",73.809524
11818,"Letter from John H. McCray to Dr. E. J. Cling,...","McCray, John Henry, 1910-1987","McCray, John Henry, 1910-1987",1946-09-28 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,Letter from John H. McCray to Dr. E. J. Cling ...,...,213,True,True,False,False,False,"['Special Char Artifacts', 'General Artifacts']","['┬ú&ΓÇó', '┬úΓÇó', '\\\\\\\\', '\\\\\\\\', 'Γ...","Sept. 28, 1946\nJ. Cling\n583 King St.\nCharle...",90.476190
11819,Letter from Mrs. E.M. Parker to Mildred Chestn...,"McCray, John Henry, 1910-1987","McCray, John Henry, 1910-1987",1946-09-30 00:00:00,NaN,Manuscripts; Accession 11294.,Lighthouse and Informer,NaN,NaN,Letter from Mrs. E.M. Parker to Mildred Chestn...,...,505,True,False,False,False,False,['Special Char Artifacts'],['ΓÇÖ'],"loja Line, St.\nCharleston, S.C\nSept. 30,1946...",96.385542

In [5]:
def save_csv(df, title):
    df.to_csv(title,
          index=False,
          encoding='utf-8',
          quoting=csv.QUOTE_NONNUMERIC,   
          escapechar='\\',
          lineterminator='\n')

save_csv(df, Paths.mccray_folder + "october_sprint/subset/McCray d_m1940s.csv")
len(df)

# save_csv(df, Paths.mccray_folder + "changed_data/McCray,1940s,5126-BASIC,V1.csv")

# df_lim = df[["CONTENTdm number", "Original Transcript"]]

# save_csv(df_lim, Paths.mccray_folder + "changed_data/McCray,1940s,5126-NUMS,V1.csv")

3438

In [6]:
# def non_letter_non_number_percentage(s: str) -> float:
#     # Remove all whitespace
#     s = s.replace(" ", "")
#     if not s:
#         return 0.0
    
#     total_chars = len(s)
#     non_alphanumeric = sum(1 for c in s if not (c.isalpha() or c.isdigit()))
    
#     return (non_alphanumeric / total_chars) * 100

# # Apply non_letter_non_number_percentage to Semi-clean Transcript column
# df['Non-AlphaNum %'] = df['Semi-clean Transcript'].apply(
#     lambda x: non_letter_non_number_percentage(str(x)) if pd.notna(x) else 0.0
# )

# # Display some statistics about the new column
# print("Non-Alphanumeric Percentage Statistics:")
# print(f"Mean: {df['Non-AlphaNum %'].mean():.1f}%")
# print(f"Median: {df['Non-AlphaNum %'].median():.1f}%")
# print(f"Min: {df['Non-AlphaNum %'].min():.1f}%")
# print(f"Max: {df['Non-AlphaNum %'].max():.1f}%")

# # Show distribution
# print("\nDistribution:")
# print(f"<10% non-alphanumeric: {(df['Non-AlphaNum %'] < 10).sum()} documents")
# print(f"10-20% non-alphanumeric: {((df['Non-AlphaNum %'] >= 10) & (df['Non-AlphaNum %'] < 20)).sum()} documents")
# print(f"20-30% non-alphanumeric: {((df['Non-AlphaNum %'] >= 20) & (df['Non-AlphaNum %'] < 30)).sum()} documents")
# print(f"30%+ non-alphanumeric: {(df['Non-AlphaNum %'] >= 30).sum()} documents")

# # Show examples of high non-alphanumeric percentage (likely OCR issues)
# print("\nExamples with high non-alphanumeric percentages:")
# high_non_alphanum = df[df['Non-AlphaNum %'] > 30].head(3)
# for idx, row in high_non_alphanum.iterrows():
#     print(f"\nNon-AlphaNum %: {row['Non-AlphaNum %']:.1f}%")
#     print(f"Text: {str(row['Semi-clean Transcript'])[:100]}...")

# save_csv(df, Paths.mccray_folder + "october_sprint/subset/McCray d_m1940s.csv")